### ISSUE TITLE
UX improvement  Add context menu for adding a label or instruction on the window how to add a label.

### ISSUE THREAD

**Issue by Donaldpherman** [curzona/local-history-visual-studio#4]
It's not obvious how to add a label.  I want to right click for a context menu but nothing shows up.  At least a text label could be added somewhere on the window.  Use "L" to add a label.
![image](https://user-images.githubusercontent.com/3155787/55900767-c4f56680-5b7c-11e9-8742-1ec4e423e0dd.png)

**Comment by SugoiDev** [comment]
I think you meant to submit this issue to my fork at [LostAlloy/LocalHistory-for-Visual-Studio/issues](https://github.com/LostAlloy/LocalHistory-for-Visual-Studio/issues), since this version doesn't support labels.

This is actually the first issue there: [Right click menu](https://github.com/LostAlloy/LocalHistory-for-Visual-Studio/issues/1)

**Comment by Donaldpherman** [comment]
Oh sorry about that.  I'll close this issue.
